export const Posts = [
  {
    id: 1,
    title: "Introduction to Python",
    img: "https://unsplash.com/photos/C_THRvqBRh8",
    date: "Jan 13 2023",
    upvote: 120,
    comments: 45,
  },
  {
    id: 2,
    title: "Advanced JavaScript Techniques",
    img: "https://unsplash.com/photos/W5mj1ZT7xLw",
    date: "Jan 13 2023",
    upvote: 98,
    comments: 34,
  },
  {
    id: 3,
    title: "Building Responsive Websites",
    img: "https://unsplash.com/photos/HGV2TfOh0ns",
    date: "Jan 13 2023",
    upvote: 110,
    comments: 50,
  },
  {
    id: 4,
    title: "Understanding CSS Grid",
    img: "https://unsplash.com/photos/ke0nc8-58MQ",
    date: "Jan 13 2023",
    upvote: 76,
    comments: 20,
  },
  {
    id: 5,
    title: "React vs Angular: A Comparison",
    img: "https://unsplash.com/photos/oMpAz-DN-9I",
    date: "Jan 13 2023",
    upvote: 150,
    comments: 60,
  },
  {
    id: 6,
    title: "Getting Started with Vue.js",
    img: "https://unsplash.com/photos/b_79nOqf95I",
    date: "Jan 13 2023",
    upvote: 85,
    comments: 25,
  },
  {
    id: 7,
    title: "Python Data Science Libraries",
    img: "https://unsplash.com/photos/MYbhN8KaaEc",
    date: "Jan 13 2023",
    upvote: 200,
    comments: 70,
  },
  {
    id: 8,
    title: "JavaScript ES6 Features",
    img: "https://unsplash.com/photos/IgUR1iX0mqM",
    date: "Jan 13 2023",
    upvote: 95,
    comments: 30,
  },
  {
    id: 9,
    title: "Node.js for Backend Development",
    img: "https://unsplash.com/photos/tGBXiHcPKrM",
    date: "Jan 13 2023",
    upvote: 125,
    comments: 40,
  },
  {
    id: 10,
    title: "Introduction to TypeScript",
    img: "https://unsplash.com/photos/ln5drpv_ImI",
    date: "Jan 13 2023",
    upvote: 105,
    comments: 35,
  },
  {
    id: 11,
    title: "Effective Git and GitHub Usage",
    img: "https://unsplash.com/photos/KE0nC8-58MQ",
    date: "Jan 13 2023",
    upvote: 135,
    comments: 55,
  },
  {
    id: 12,
    title: "DevOps Best Practices",
    img: "https://unsplash.com/photos/5aiRb5f464A",
    date: "Jan 13 2023",
    upvote: 145,
    comments: 65,
  },
  {
    id: 13,
    title: "Building REST APIs with Express.js",
    img: "https://unsplash.com/photos/wpOa2AvTSdE",
    date: "Jan 13 2023",
    upvote: 115,
    comments: 42,
  },
  {
    id: 14,
    title: "GraphQL vs REST: A Comparison",
    img: "https://unsplash.com/photos/ke0nc8-58MQ",
    date: "Jan 13 2023",
    upvote: 90,
    comments: 28,
  },
  {
    id: 15,
    title: "Docker for Beginners",
    img: "https://unsplash.com/photos/_H6wpor9mjs",
    date: "Jan 13 2023",
    upvote: 160,
    comments: 80,
  },
  {
    id: 16,
    title: "Kubernetes: An Introduction",
    img: "https://unsplash.com/photos/YTBiOqQXHvE",
    date: "Jan 13 2023",
    upvote: 140,
    comments: 60,
  },
  {
    id: 17,
    title: "Microservices Architecture",
    img: "https://unsplash.com/photos/qHJjgu6qYVI",
    date: "Jan 13 2023",
    upvote: 170,
    comments: 90,
  },
  {
    id: 18,
    title: "Understanding Webpack",
    img: "https://unsplash.com/photos/rYrJmH7kKFs",
    date: "Jan 13 2023",
    upvote: 88,
    comments: 27,
  },
  {
    id: 19,
    title: "Introduction to Machine Learning",
    img: "https://unsplash.com/photos/m_HRfLhgABo",
    date: "Jan 13 2023",
    upvote: 220,
    comments: 100,
  },
  {
    id: 20,
    title: "AI and Deep Learning Basics",
    img: "https://unsplash.com/photos/gMsnXqILjp4",
    date: "Jan 13 2023",
    upvote: 250,
    comments: 120,
  },
];
